name: Test CediRates Frontend CI/CD

on:
  push:
    branches:
      - staging

jobs:
  build-react-app:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      - uses: actions/checkout@v2
        with:
          ref: staging

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: List build directory contents
        run: ls -la .next

      - name: Archive build artifacts
        run: tar -czf build-artifacts.tar.gz .next public

      - name: Copy build artifacts to server
        uses: appleboy/scp-action@master
        with:
          host: 51.116.110.49
          username: azureuser
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          source: build-artifacts.tar.gz
          target: /home/azureuser/cedi-rates-frontend-test/

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: 51.116.110.49
          username: azureuser
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/cedi-rates-frontend-test
            tar -xzf build-artifacts.tar.gz
            /home/azureuser/.nvm/versions/node/v18.20.4/bin/pm2 restart cedi-rates-frontend-test
