name: CediRates Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-react-app:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - uses: actions/setup-node@v2.5.2
        with:
          node-version: "18"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build
        continue-on-error: false

      - name: List build directory contents
        run: ls -la .next

      - name: Archive build artifacts
        run: tar -czf build-artifacts.tar.gz .next public

      - name: Copy build artifacts to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: CediRates
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: build-artifacts.tar.gz
          target: /home/CediRates/projects/cedi-rates-frontend/
          timeout: 60s

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: CediRates
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/CediRates/projects/cedi-rates-frontend
            tar -xzf build-artifacts.tar.gz
            pm2 restart cedi-rates-frontend
          timeout: 60s
